/**
 * Static manifest of the fictional-brand showcase logos generated by
 * scripts/gen-showcase.mjs (FLUX.2-pro) into public/showcase/. Hand-committed
 * so it's SSR-safe (no directory scan, no runtime fetch). Order is interleaved
 * by style so the carousel rows look varied. All brands are invented, no real
 * trademarks.
 */
export type ShowcaseLogo = { src: string; name: string; style: string };

export const SHOWCASE: ShowcaseLogo[] = [
  { src: "/showcase/tidewell.png", name: "Tidewell", style: "Minimal" },
  { src: "/showcase/cobalt.png", name: "Cobalt", style: "Geometric" },
  { src: "/showcase/halcyon.png", name: "Halcyon", style: "Gradient" },
  { src: "/showcase/ferncrest.png", name: "Ferncrest", style: "Mascot" },
  { src: "/showcase/emberoak.png", name: "Ember & Oak", style: "Hand-drawn" },
  { src: "/showcase/vellum.png", name: "Vellum", style: "Luxury" },
  { src: "/showcase/sunsetdiner.png", name: "Sunset Diner", style: "Retro" },
  { src: "/showcase/quanta.png", name: "Quanta", style: "3D" },
  { src: "/showcase/northpeak.png", name: "Northpeak", style: "Minimal" },
  { src: "/showcase/axiom.png", name: "Axiom", style: "Geometric" },
  { src: "/showcase/novastream.png", name: "Nova", style: "Gradient" },
  { src: "/showcase/pawsome.png", name: "Pawsome", style: "Mascot" },
  { src: "/showcase/marigold.png", name: "Marigold", style: "Hand-drawn" },
  { src: "/showcase/noirco.png", name: "Noir & Co", style: "Luxury" },
  { src: "/showcase/riverside.png", name: "Riverside", style: "Retro" },
  { src: "/showcase/volt.png", name: "Volt", style: "3D" },
  { src: "/showcase/lumen.png", name: "Lumen", style: "Minimal" },
  { src: "/showcase/hexa.png", name: "Hexa", style: "Geometric" },
  { src: "/showcase/auric.png", name: "Auric", style: "Gradient" },
  { src: "/showcase/hootly.png", name: "Hootly", style: "Mascot" },
  { src: "/showcase/wildhoney.png", name: "Wildhoney", style: "Hand-drawn" },
  { src: "/showcase/aurelia.png", name: "Aurelia", style: "Luxury" },
  { src: "/showcase/route9.png", name: "Route 9", style: "Retro" },
  { src: "/showcase/orbital.png", name: "Orbital", style: "3D" },
  { src: "/showcase/paperline.png", name: "Paperline", style: "Minimal" },
  { src: "/showcase/vertex.png", name: "Vertex", style: "Geometric" },
  { src: "/showcase/prism.png", name: "Prism", style: "Gradient" },
  { src: "/showcase/bramble.png", name: "Bramble", style: "Mascot" },
  { src: "/showcase/saltwater.png", name: "Saltwater", style: "Hand-drawn" },
  { src: "/showcase/monarch.png", name: "Monarch", style: "Luxury" },
  { src: "/showcase/goldenrod.png", name: "Goldenrod", style: "Retro" },
  { src: "/showcase/cubeworks.png", name: "Cubeworks", style: "3D" },
];
